### PR TITLE
Ugly patch to support future parser's Puppet Types (fixes #1)

### LINKED ISSUE #1: Support type system in cases
With Puppet 4's Type system you can have unquoted strings in case statements, like so:

```puppet
case $value {
  Integer: { notice('yes int')}
  Array: { notice('yes array')}
  'Debian': { notice('this is Sparta')}
  default: { notice('something else')}
}
```

However, this will cause the plugin to furiously complain about the first 2 lines in the case statement as it considers that they need to be quoted but in this case will actually do a type check. Line 3 will be OK since that's quoted so will check the assigned value of `$value` and compare to that instead.

Any of the types listed [here](https://github.com/puppetlabs/puppet-specifications/blob/master/language/types_values_variables.md) should be allowed unquoted in a `case` statement.

### PR DESCRIPTION
**Pull request by mcanevet**

### CODE REVIEW

**Comment by mcanevet** [comment]
Better approach : https://github.com/rodjek/puppet-lint/pull/435

**Comment by igalic** [comment]
@mcanevet should we close this in favour of https://github.com/rodjek/puppet-lint/pull/435 ?

**Comment by mcanevet** [comment]
@igalic once https://github.com/rodjek/puppet-lint/pull/435 is merged sure, but in the mean time I see no other solution than merging this...
@daenney do you need this feature urgently?

**Comment by daenney** [comment]
It's not super-urgent. If anything what I'm doing right now is just disabling this check in places with comments but it feels meh to do so.

**Comment by bastelfreak** [comment]
https://github.com/rodjek/puppet-lint/pull/435 is still open. I will merge this one. We can revert in the next years if anything happens at puppet-lint...

**Pull request merged**
